### ISSUE TITLE
esp8266 crash after browser visit

### ISSUE THREAD

**Issue by shinnlu** [ayushsharma82/EasyUI#1]
i just install EasyUI and upload example to esp8266, it's working and show IP Address in console.
but it's crash after browser visiting.
`Exception (3):
epc1=0x4000bef4 epc2=0x00000000 epc3=0x00000000 excvaddr=0x4025568e depc=0x00000000

ctx: cont 
sp: 3fff0750 end: 3fff0a60 offset: 01a0

>>>stack>>>
3fff08f0:  3ffef94c 000000e8 3fff0930 4020d371  
3fff0900:  00000001 3fff1c34 3fff0930 4020d3c2  
3fff0910:  4025568e 000004de 3ffef7c8 4020d294  
3fff0920:  00000001 3fff1c34 3ffef7c8 402092c5  
3fff0930:  3fff39ac 000003af 000003ad 4020d2f0  
3fff0940:  3fff36ac 00000001 00000000 00000000  
3fff0950:  00000000 0000048c 0000048c 4010020c  
3fff0960:  00000001 00000001 3fff346c 4020eceb  
3fff0970:  00000000 3fffdad0 3fff346c 40209f5a  
3fff0980:  3fff346c 3fff1c74 3fff346c 40209f96  
3fff0990:  00000000 00000000 00000000 4020d4a0  
3fff09a0:  3fff346c 3fff1c74 3fff1c34 4020a029  
3fff09b0:  3fff36ac 0000000f 00000001 3fff2514  
3fff09c0:  3fff1c74 000000a8 4020db74 00000001  
3fff09d0:  00000001 40209558 0000000f 402010a3  
3fff09e0:  00000000 3fff2514 3fff2894 3ffefa2c  
3fff09f0:  00000001 3fff1c58 3fff1c34 4020a263  
3fff0a00:  3ffe8480 00000000 000003e8 3ffefa2c  
3fff0a10:  3fffdad0 00000000 3fff2514 4020c934  
3fff0a20:  3fffdad0 00000000 3ffef7c8 40207bc1  
3fff0a30:  00000000 00000000 3ffefa25 40206a80  
3fff0a40:  3fffdad0 00000000 3ffefa25 4020dbc0  
3fff0a50:  feefeffe feefeffe 3ffefa40 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)
`

`Exception 3: LoadStoreError: Processor internal physical address or data error during load or store`

**Comment by shinnlu** [comment]
`Exception 3: LoadStoreError: Processor internal physical address or data error during load or store
Decoding 23 results
0x4020d371: UdpContext::append(char const*, unsigned int) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 283
:  (inlined by) WiFiUDP::write(unsigned char const*, unsigned int) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 204
0x4020d3c2: WiFiUDP::write(unsigned char const*, unsigned int) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 283
0x4020d294: WiFiUDP::available() at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 283
0x402092c5: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x4020d2f0: WiFiUDP::write(unsigned char const*, unsigned int) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 283
0x4010020c: _umm_free at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/umm_malloc/umm_malloc.c line 1287
0x4020eceb: ESP8266WebServer::_parseFormUploadAborted() at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/Parsing.cpp line 584
0x40209f5a: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x40209f96: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x4020d4a0: UdpContext::send(ip_addr*, unsigned short) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 283
:  (inlined by) WiFiUDP::endPacket() at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/WiFiUdp.cpp line 191
0x4020a029: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x4020db74: ESP8266WebServer::header(String) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h line 53
0x40209558: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x402010a3: itoa at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/core_esp8266_noniso.c line 45
0x4020a263: GetRidOfurlCharacters(String) at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x4020c934: ESP8266WiFiSTAClass::begin(char const*, char const*, int, unsigned char const*, bool) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp line 145
0x40207bc1: handlePing() at /Users/shinn/Documents/Arduino/libraries/ESP8266Ping/src/ESP8266Ping.impl.h line 65
0x40206a80: spiffs_gc_clean at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/spiffs/spiffs_gc.c line 432
0x4020dbc0: ESP8266WebServer::collectHeaders(char const**, unsigned int) at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h line 53
0x40100718: cont_norm at /Users/shinn/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/cont.S line 109
`

**Comment by ayushsharma82** [comment]
Please Use **Latest** Versions of Dependencies.
I was not able to Replicate the Bug with the Settings and Info you Gave me,
